#$schema: https://www.flowlauncher.com/schemas/settings-template.schema.json
body:
  - type: input
    attributes:
      name: karakeepBaseAddress
      label: Karakeep Base Address
      description: Karakeep Base Url (e.g. https://karakeep.example.com)
  - type: passwordBox
    attributes:
      name: karakeepApiKey
      label: Karakeep API Key
